name: Backend CI

on: [push]

jobs:	
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: yarn --frozen-lockfile --silent
      - name: Build app
        run: yarn build --if-present